export const API_NAMESPACE_CLIENTS = [
  "V1CandlesClient",
  "V1CollateralClient",
  "V1ExchangeClient",
  "V1FundingClient",
  "V1InviteClient",
  "V1MarketsClient",
  "V1NotificationsClient",
  "V1OrderbookClient",
  "V1OrdersClient",
  "V1TradersClient",
  "V1TradesClient",
] as const;

export const HTTP_CLIENT_PRESENT_METHODS = [
  "candles",
  "collateral",
  "exchange",
  "funding",
  "invite",
  "markets",
  "notifications",
  "orderbook",
  "orders",
  "traders",
  "trades",
  "auth",
  "sessionManager",
  "exportAuthSnapshot",
] as const;

export const HTTP_CLIENT_ABSENT_METHODS = [
  "publicApi",
  "getMarkets",
  "getTrader",
] as const;

export const HTTP_RESOURCE_PRESENT_METHODS = {
  candles: ["getCandles"],
  collateral: [
    "getTraderCollateralHistory",
    "getUserCollateralHistory",
    "getAllUserCollateralHistory",
  ],
  markets: ["getMarkets", "getMarket", "getMarketStatsHistory"],
  exchange: ["getSnapshot"],
  orderbook: ["getOrderbook"],
  funding: ["getTraderFundingHistory", "getUserFundingHourly"],
  invite: ["activateInvite"],
  notifications: [
    "getNotificationsByTrader",
    "ackUpToTimestamp",
    "ackNotifications",
  ],
  orders: [
    "getTraderOrderHistory",
    "cancelConditionalOrder",
    "placeIsolatedLimitOrder",
    "placeIsolatedMarketOrder",
    "getTraderOrderHistoryV2",
  ],
  traders: [
    "getTrader",
    "getTraderState",
    "getTraderStateSnapshot",
    "getTraderPnl",
    "getTraderCapabilities",
    "getTraderPortfolioValues",
    "getTraderPnlValues",
    "getTraderMarketPnl",
  ],
  trades: [
    "getTraderTradesHistory",
    "getMarketFills",
    "getTraderTradeHistoryV2",
  ],
} as const;

export const HTTP_RESOURCE_ABSENT_METHODS = {
  markets: ["getPriceHistory"],
  orders: ["getOrderDetails"],
  traders: ["getActiveTraders", "getTraderPendingEscrowRequests"],
} as const;

export const ROOT_ABSENT_PROPERTIES = [
  "PUBLIC_API_PATHS",
  "PUBLIC_API_PATH_SET",
  "PUBLIC_V1_DATA_PATHS",
  "PUBLIC_V1_DATA_PATH_SET",
  "resolvePublicApiPath",
  "RISE_ROUTE_CATALOG",
  "getRiseRouteMeta",
] as const;

export const ROOT_PRESENT_PROPERTIES = [
  "auth",
  "createPhoenixClient",
  "createPhoenixIxClient",
  "createPhoenixRpcClient",
  "buildLimitOrderPacketFromMarketParams",
  "buildMarketOrderPacketFromMarketParams",
  "buildDepositFundsIxResolved",
  "buildWithdrawFundsIxResolved",
  "buildTransferCollateralIxResolved",
  "buildTransferCollateralChildToParentIxResolved",
  "buildCancelAllIxResolved",
  "buildCancelOrdersByIdIxResolved",
  "buildCancelStopLossIxResolved",
  "buildCreateEscrowRequestIxResolved",
  "buildDelegateTraderIxResolved",
  "buildEmberDepositIxResolved",
  "buildEmberWithdrawIxResolved",
  "buildCancelConditionalOrder",
  "buildCreateConditionalOrdersAccount",
  "buildDepositIxsResolved",
  "buildWithdrawIxsResolved",
  "buildPlaceAttachedConditionalOrder",
  "buildPlaceLimitOrderIxResolved",
  "buildPlaceLimitOrderWithConditionals",
  "buildPlaceMarketOrderIxResolved",
  "buildPlacePostOnlyOrderIxResolved",
  "buildPlacePositionConditionalOrder",
  "buildPlaceStopLoss",
  "buildPlaceStopLossIxResolved",
  "buildRegisterTraderIxResolved",
  "buildSyncParentToChildIxResolved",
  "getPhoenixConditionalOrdersAddress",
  "createAllMidsAdapter",
  "createCandlesAdapter",
  "createExchangeAdapter",
  "createExchangeStatusAdapter",
  "createFillsAdapter",
  "createFundingRateAdapter",
  "createL2BookAdapter",
  "createMarkPriceAdapter",
  "createMarketAdapter",
  "createMarketStatsAdapter",
  "createNotificationsAdapter",
  "createOrderbookAdapter",
  "createPhoenixExchangeCache",
  "createPhoenixExchangeMetadata",
  "createPhoenixExchangeMarketSelection",
  "createPhoenixMarketData",
  "createPhoenixMarketDataSelection",
  "createPhoenixOrderbookManager",
  "createPhoenixTraderStateManager",
  "createTraderStateStore",
  "projectExchangeMarket",
  "projectPhoenixExchangeMarketState",
  "projectPhoenixMarket",
  "projectPhoenixMarketDataSelectionState",
  "projectPhoenixMarketsBySymbol",
  "createPhoenixExchangeCacheStore",
  "createPhoenixWsClient",
  "createPhoenixWsFacade",
  "createTraderStateAdapter",
  "registerSubscription",
  "registerSubscriptions",
  "selectExchangeMarket",
  "selectExchangeMarketStatus",
  "selectMarketDataRow",
  "selectPhoenixExchangeMarket",
  "selectPhoenixExchangeMarketChange",
  "selectPhoenixExchangeMarketState",
  "selectPhoenixExchangeMarketStatus",
  "selectPhoenixMarketDataRow",
  "selectPhoenixMarkPrice",
  "selectPhoenixMidPrice",
] as const;

export const MIGRATED_INSTRUCTION_BUILDERS = [
  "buildCancelUpToIx",
  "buildPlaceMultiLimitOrderIx",
  "buildPlaceStopLossIx",
  "buildUpdateTraderStateIx",
] as const;

export const PHOENIX_CLIENT_PRESENT_PROPERTIES = [
  "streams",
  "orderPackets",
  "ixs",
  "rpc",
  "marketData",
  "orderbooks",
] as const;

export const PHOENIX_CLIENT_EXCHANGE_PROPERTIES = ["store"] as const;

export const PHOENIX_ORDER_PACKET_PROPERTIES = [
  "buildLimitOrderPacket",
  "buildMarketOrderPacket",
] as const;

export const PHOENIX_IX_PROPERTIES = [
  "orderPackets",
  "buildDepositFunds",
  "buildWithdrawFunds",
  "buildTransferCollateral",
  "buildTransferCollateralChildToParent",
  "buildCancelAll",
  "buildCancelOrdersById",
  "buildCancelStopLoss",
  "buildCreateConditionalOrdersAccount",
  "buildCreateEscrowRequest",
  "buildDelegateTrader",
  "buildEmberDeposit",
  "buildEmberWithdraw",
  "buildDepositIxs",
  "buildWithdrawIxs",
  "buildPlacePositionConditionalOrder",
  "buildPlaceStopLoss",
  "buildRegisterTrader",
  "buildSyncParentToChild",
  "placeLimitOrder",
  "placeMarketOrder",
  "placePositionConditionalOrder",
  "placePostOnlyOrder",
] as const;

export const PHOENIX_RPC_PROPERTIES = [
  "available",
  "exchange",
  "markets",
] as const;
