export const API_NAMESPACE_CLIENTS = [
  "V1CandlesClient",
  "V1CollateralClient",
  "V1ExchangeClient",
  "V1FundingClient",
  "V1InviteClient",
  "V1MarketsClient",
  "V1NotificationsClient",
  "V1OrderbookClient",
  "V1OrdersClient",
  "V1TradersClient",
  "V1TradesClient",
] as const;

export const HTTP_CLIENT_PRESENT_METHODS = [
  "candles",
  "collateral",
  "exchange",
  "funding",
  "invite",
  "markets",
  "notifications",
  "orderbook",
  "orders",
  "traders",
  "trades",
  "auth",
  "sessionManager",
  "exportAuthSnapshot",
] as const;

export const HTTP_CLIENT_ABSENT_METHODS = [
  "publicApi",
  "getMarkets",
  "getTrader",
] as const;

export const HTTP_RESOURCE_PRESENT_METHODS = {
  candles: ["getCandles"],
  collateral: [
    "getTraderCollateralHistory",
    "getUserCollateralHistory",
    "getAllUserCollateralHistory",
  ],
  markets: [
    "getMarkets",
    "getMarket",
    "getMarketStatsHistory",
    "getLatestMarketStats",
    "getLatestMarketsStats",
    "getNextCommodityMarketTransition",
    "getCommodityMarketCalendar",
    "getNextMarketCalendarTransition",
    "getMarketCalendar",
  ],
  exchange: ["buildRegisterIxs", "getSnapshot", "sendRegisterIxs"],
  orderbook: ["getOrderbook"],
  funding: ["getTraderFundingHistory", "getUserFundingHourly"],
  invite: [
    "activateInvite",
    "activateReferralTx",
    "buildActivateReferralTxRequest",
    "getReferralActivationPermission",
  ],
  notifications: [
    "getNotificationsByTrader",
    "ackUpToTimestamp",
    "ackNotifications",
  ],
  orders: [
    "getTraderOrderHistory",
    "cancelConditionalOrder",
    "placeStopLossOrder",
    "cancelStopLossOrder",
    "placeAttachedConditionalOrder",
    "placePositionConditionalOrder",
    "placeIsolatedLimitOrder",
    "placeIsolatedLimitOrderWithConditionals",
    "placeIsolatedMarketOrder",
    "getTraderOrderHistoryV2",
  ],
  traders: [
    "getTrader",
    "getTraderStateSnapshot",
    "getTraderPnl",
    "getTraderCapabilities",
    "getTraderPortfolioValues",
    "getTraderTimeWeightedReturns",
    "getTraderPnlValues",
    "getTraderMarketPnl",
  ],
  trades: [
    "getUserLiquidationHistory",
    "getTraderTradesHistory",
    "getMarketFills",
    "getTraderTradeHistoryV2",
  ],
} as const;

export const HTTP_RESOURCE_ABSENT_METHODS = {
  markets: ["getPriceHistory"],
  orders: ["getOrderDetails"],
  traders: ["getActiveTraders", "getTraderPendingEscrowRequests"],
} as const;

export const ROOT_ABSENT_PROPERTIES = [
  "PUBLIC_API_PATHS",
  "PUBLIC_API_PATH_SET",
  "PUBLIC_V1_DATA_PATHS",
  "PUBLIC_V1_DATA_PATH_SET",
  "resolvePublicApiPath",
  "RISE_ROUTE_CATALOG",
  "getRiseRouteMeta",
  "buildSetTraderCapabilitiesDelegated",
  "buildSetTraderCapabilitiesDelegatedIx",
  "buildSetTraderCapabilitiesDelegatedIxResolved",
  "TraderCapabilityToggleTarget",
] as const;

export const ROOT_PRESENT_PROPERTIES = [
  "auth",
  "decodePerpAssetMap",
  "fetchPerpAssetMap",
  "getPerpAssetMapDecoder",
  "createPhoenixClient",
  "createPhoenixIxClient",
  "createPhoenixRpcClient",
  "buildHawkeyeViewMarginIx",
  "buildHawkeyeViewMarginForAssetIx",
  "buildHawkeyeViewLiquidationPriceIx",
  "buildHawkeyeViewBboIx",
  "buildHawkeyeViewFundingIx",
  "buildActivateReferralTxRequest",
  "buildReferralActivationTransaction",
  "getReferralActivationTraderState",
  "hasReferralActivationCapabilities",
  "referralActivationExchangeAccountsFromSnapshot",
  "serializeReferralActivationSignedTransaction",
  "decodeHawkeyeReturnData",
  "encodeHawkeyeSimulationTransaction",
  "TraderPreferenceKind",
  "decodeTraderPreferenceFlags",
  "encodeTraderPreferences",
  "HAWKEYE_PROGRAM_ADDRESS",
  "HAWKEYE_SIMULATION_COMPUTE_UNIT_LIMIT",
  "calculateLiquidationPriceUsd",
  "computeMarketLiquidationPriceFromMargin",
  "computeSubaccountLiquidationPricesFromInputs",
  "computeSubaccountLiquidationPricesFromMargin",
  "computeTraderLiquidationPricesFromInputs",
  "computeTraderLiquidationPricesFromMargin",
  "simulateMarginFromInputs",
  "simulateMarginScenariosFromInputs",
  "simulatePositionFillFromInputs",
  "buildLimitOrderPacketFromMarketParams",
  "buildMarketOrderPacketFromMarketParams",
  "computeDraftOrderMarginRequirementFromInputs",
  "computeDraftOrderMarginRequirementFromSnapshot",
  "computeMaxDraftOrderSizeForAvailableMarginFromInputs",
  "computeMaxDraftOrderSizeForAvailableMarginFromSnapshot",
  "buildDepositFundsIxResolved",
  "buildFlameAtomicDepositFlow",
  "buildFlameDepositToPhoenixIx",
  "buildFlameDepositFundingFlow",
  "buildWithdrawFundsIxResolved",
  "buildTransferCollateralIxResolved",
  "buildTransferCollateralChildToParentIxResolved",
  "buildCancelAllIxResolved",
  "buildCancelOrdersByIdIxResolved",
  "buildCancelStopLossIxResolved",
  "buildCancelUpToIxResolved",
  "buildUncrossCrankIxResolved",
  "buildCreateEscrowRequestIxResolved",
  "buildDelegateTraderIxResolved",
  "buildEmberDepositIxResolved",
  "buildEmberWithdrawIxResolved",
  "buildCancelConditionalOrder",
  "buildCancelUpTo",
  "cancelUpToOrders",
  "buildUncrossCrank",
  "uncrossCrank",
  "buildCreateConditionalOrdersAccount",
  "buildDepositIxsResolved",
  "buildSplTokenTransfer",
  "buildWithdrawIxsResolved",
  "TP_SL_MAX_SLIPPAGE_BPS",
  "buildTakeProfitStopLossTriggerOrders",
  "buildTriggerOrderParams",
  "executionPriceFromSlippageBps",
  "normalizeTriggerOrderParams",
  "buildPlaceAttachedConditionalOrder",
  "buildPlaceLimitOrderIxResolved",
  "buildPlaceLimitOrderWithConditionals",
  "buildPlaceMarketOrderDelegated",
  "buildPlaceMarketOrderDelegatedIxResolved",
  "buildPlaceMarketOrderIxResolved",
  "placeMarketOrderDelegated",
  "buildPlacePostOnlyOrderIxResolved",
  "buildPlacePositionConditionalOrder",
  "buildPlaceStopLoss",
  "buildPlaceStopLossIxResolved",
  "buildRegisterTraderIxResolved",
  "buildOnboardTraderDelegated",
  "buildOnboardTraderDelegatedIxResolved",
  "buildSyncParentToChildIxResolved",
  "deriveFlameDepositToPhoenixAddresses",
  "deriveFlameDepositAddress",
  "deriveFlameDepositAddresses",
  "deriveFlameGlobalStateAddress",
  "deriveFlameProxyAuthorityAddress",
  "FLAME_PROGRAM_ADDRESS",
  "BETA_USDC_MINT_ADDRESS",
  "EMBER_STATE_ADDRESS",
  "resolvePhoenixBuilderAddresses",
  "getPhoenixConditionalOrdersAddress",
  "createAllMidsAdapter",
  "createCandlesAdapter",
  "createExchangeAdapter",
  "createExchangeStatusAdapter",
  "createFillsAdapter",
  "createFundingRateAdapter",
  "createL2BookAdapter",
  "createMarkPriceAdapter",
  "createMarketAdapter",
  "createMarketStatsAdapter",
  "createNotificationsAdapter",
  "createOrderbookAdapter",
  "createPhoenixExchangeCache",
  "createPhoenixExchangeMetadata",
  "createPhoenixExchangeMarketSelection",
  "createPhoenixMarketData",
  "createPhoenixMarketDataSelection",
  "createPhoenixOrderbookManager",
  "createPhoenixTraderStateManager",
  "createTraderStateStore",
  "projectExchangeMarket",
  "projectPhoenixExchangeMarketState",
  "projectPhoenixMarket",
  "projectPhoenixMarketDataSelectionState",
  "projectPhoenixMarketsBySymbol",
  "createPhoenixExchangeCacheStore",
  "createPhoenixWsClient",
  "createPhoenixWsFacade",
  "createTraderStateAdapter",
  "registerSubscription",
  "registerSubscriptions",
  "selectExchangeMarket",
  "selectExchangeMarketMetadata",
  "selectExchangeMarketStatus",
  "selectMarketDataRow",
  "selectPhoenixExchangeMarket",
  "selectPhoenixExchangeMarketChange",
  "selectPhoenixExchangeMarketMetadata",
  "selectPhoenixExchangeMarketState",
  "selectPhoenixExchangeMarketStatus",
  "selectPhoenixMarketDataRow",
  "selectPhoenixMarkPrice",
  "selectPhoenixMidPrice",
] as const;

export const MIGRATED_INSTRUCTION_BUILDERS = [
  "buildCancelUpToIx",
  "buildUncrossCrankIx",
  "buildPlaceMultiLimitOrderIx",
  "buildOnboardTraderDelegatedIx",
  "buildPlaceStopLossIx",
  "buildUpdateTraderStateIx",
] as const;

export const PHOENIX_CLIENT_PRESENT_PROPERTIES = [
  "streams",
  "orderPackets",
  "ixs",
  "rpc",
  "marketData",
  "orderbooks",
] as const;

export const PHOENIX_CLIENT_EXCHANGE_PROPERTIES = ["store"] as const;

export const PHOENIX_ORDER_PACKET_PROPERTIES = [
  "buildLimitOrderPacket",
  "buildMarketOrderPacket",
] as const;

export const PHOENIX_IX_PROPERTIES = [
  "orderPackets",
  "buildDepositFunds",
  "buildWithdrawFunds",
  "buildTransferCollateral",
  "buildTransferCollateralChildToParent",
  "buildCancelAll",
  "buildCancelOrdersById",
  "buildCancelUpTo",
  "buildUncrossCrank",
  "buildCancelStopLoss",
  "buildCreateConditionalOrdersAccount",
  "buildCreateEscrowRequest",
  "buildDelegateTrader",
  "buildEmberDeposit",
  "buildEmberWithdraw",
  "buildDepositIxs",
  "buildWithdrawIxs",
  "buildPlacePositionConditionalOrder",
  "buildPlaceStopLoss",
  "buildRegisterTrader",
  "buildOnboardTraderDelegated",
  "buildSyncParentToChild",
  "buildPlaceMarketOrderDelegated",
  "placeLimitOrder",
  "placeMarketOrder",
  "placeMarketOrderDelegated",
  "placePositionConditionalOrder",
  "placePostOnlyOrder",
  "buildHawkeyeViewMargin",
  "buildHawkeyeViewMarginForAsset",
  "buildHawkeyeViewLiquidationPrice",
  "buildHawkeyeViewBbo",
  "buildHawkeyeViewFunding",
] as const;

export const PHOENIX_RPC_PROPERTIES = [
  "available",
  "exchange",
  "markets",
  "hawkeye",
] as const;
