[package]
edition      = "2021"
name         = "rise-close-position-and-withdraw-cli"
publish      = false
rust-version = "1.84.0"
version      = "0.1.0"

[dependencies]
borsh = "=1.6.0"
clap = { version = "4.5", features = ["derive", "env"] }
phoenix-rise = { path = "../../../rust/sdk", default-features = false, features = [
  "api",
  "sdk",
] }
rise-close-position-and-withdraw = { path = ".." }
solana-commitment-config = "~3.1"
solana-compute-budget-interface = "~3.0"
solana-instruction = { version = "~3.0", default-features = false, features = [
  "std",
] }
solana-keypair = "~3.1"
solana-pubkey = { version = "~3.0", features = ["curve25519"] }
solana-rpc-client = "~3.1"
solana-signer = "~3.0"
solana-transaction = "~3.1"
tokio = { version = "1.44", features = ["macros", "rt-multi-thread"] }

[profile.ci]
inherits = "dev"
# Full debug in CI builds is unnecessary and makes cache artifacts large.
debug = "line-tables-only"
